baseURL = 'https://reno-one.vercel.app/' # Replace with your actual Vercel URL
languageCode = 'en-us'
title = 'Rafael Reno'
theme = 'PaperMod'

[params]
    # This tells PaperMod to show a nice "Profile Mode" on the homepage
    homeInfoParams:
        Title: "Rafael Reno"
        Content: "Quant. Sailor. Artist. | Markets | Science | Sports | Logbook"

[menu]
  [[menu.main]]
    name = "Markets"
    url = "/markets"
    weight = 10
  [[menu.main]]
    name = "Science"
    url = "/science"
    weight = 20
  [[menu.main]]
    name = "Sports"
    url = "/sports"
    weight = 30
  [[menu.main]]
    name = "Logbook"
    url = "/logbook"
    weight = 40
